# register as aggregated apiserver; this has a number of benefits:
#
# - allows other kubernetes components to talk to the the admission webhook using the `kubernetes.default.svc` service
# - allows other kubernetes components to use their in-cluster credentials to communicate with the webhook
# - allows you to test the webhook using kubectl
# - allows you to govern access to the webhook using RBAC
# - prevents other extension API servers from leaking their service account tokens to the webhook
#
# for more information, see: https://kubernetes.io/blog/2018/01/extensible-admission-is-beta
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1.admission.autoscaling.openshift.io
spec:
  group: admission.autoscaling.openshift.io
  version: v1
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: clusterresourceoverride
    namespace: cluster-resource-override
  caBundle: SERVICE_SERVING_CERT_CA

